### ISSUE TITLE
Facing issue while running sql statements directly on ehrbase in version 23

### ISSUE THREAD

**Issue by manci22lc** [ehrbase/ehrbase#1072]
# Environment information

EHRbase version:0.23.0
openEHR_SDK version:1.19.0
Archie version:2.0.1
PostgreSQL version: PostgreSQL 13.7, compiled by Visual C++ build 1914, 64-bit
Java Runtime version: Oracle Corporation 17.0.4.v20221004

# Steps to reproduce

Note : We have current data in ehrbase(20 version), and we are planning to upgrade to 23 version

Run docker Image of 23 version DB pointed to existing ehrbase(20 version)
Flyway migration is success, took about 50 odd mins to start ehrbase application

In postgres, run any  sql statements 
select * from ehr.ehr  limit 10;

# Actual result

ERROR:  unrecognized configuration parameter "ehrbase.current_tenant"
SQL state: 42704

# Expected result

 Should have Returned DB rows

# Further information

**Comment by vidi42** [comment]
@manci22lc this is because ehrbase supports storing and accessing tenant-separated data. For that there are [policies in place for each table ](https://github.com/ehrbase/ehrbase/blob/7dc6b1c02595e29e26a2fcb2dba43ddc48c7c219/base/src/main/resources/db/migration/V74__add_rls_for_tenant.sql#L98) to read the tenant identifier from the current_setting('ehrbase.current_tenant').

For accessing data through SQL directly, you will need to set this manually in your SQL session
```SQL
-- set current_tenant to default tenant
SET ehrbase.current_tenant='1f332a66-0e57-11ed-861d-0242ac120002'
```
