### ISSUE TITLE
Error when reading a composition that has a provider name set

### ISSUE THREAD

**Issue by robert-hunter-nes** [ehrbase/ehrbase#141]
I have seena n issue where if I set the provider name field on an evaluation in my composition I get an error. 

```
{
    "error": "DB inconsistency:org.ehrbase.serialisation.UnmarshalException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token\n at [Source: (String)\"{\"archetype_node_id\":\"openEHR-EHR-COMPOSITION.report.v1\",\"_type\":\"COMPOSITION\",\"name\" : {\n    \"_type\" : \"DV_TEXT\",\n    \"value\" : \"NDS RESPECT Form\"},\"content\":[{\"archetype_node_id\":\"openEHR-EHR-SECTION.respect_headings.v0\",\"archetype_node_id\":\"openEHR-EHR-SECTION.respect_headings.v0\",\"_type\":\"SECTION\",\"items\":[{\"archetype_node_id\":\"at0001\",\"archetype_node_id\":\"at0001\",\"_type\":\"SECTION\",\"items\":[{\"archetype_node_id\":\"at0005\",\"archetype_node_id\":\"at0005\",\"_type\":\"SECTION\",\"items\":[{\"name\":{\"value\"\"[truncated 14059 chars]; line: 3, column: 3224] (through reference chain: com.nedap.archie.rm.composition.Composition[\"content\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Section[\"items\"]->java.util.ArrayList[2]->com.nedap.archie.rm.composition.Section[\"items\"]->java.util.ArrayList[1]->com.nedap.archie.rm.composition.Evaluation[\"provider\"]->com.nedap.archie.rm.generic.PartyIdentified[\"name\"])",

    "status": "Bad Request"
}
```

The provider was set as follows

```
"provider": {
    "_type": "PARTY_IDENTIFIED",
    "name": "John Smith"
},
```

I think the problem is that the Provider name field is being treated as DvText. However looking at the reference model the name is a string, so I think should be handled differently. I have created the following PR which I think fixes the issue, at least is has in my testing, adnhasn't impacted anything else that I can see - https://github.com/ehrbase/ehrbase/pull/140
EDIT- new PR is https://github.com/ehrbase/ehrbase/pull/143

Can I ask, before I forget, please excuse my ignorance, openEHR is still new to me. When looking through the code, I notice we use JacksonUtil to deserialise, why is that not used for serialising also?

**Comment by chevalleyc** [comment]
Hi Robert,
The patterns used for serialization/deserialization differ since the serialization objective is to give a json structure compatible with JsonPath querying as implemented at DB level (following the AQL path syntax). If we were using a out-of-the-box serialization (JAXB f.e.) the querying logic would be much more complex, potentially requiring middleware processing since node qualification and corresponding identification (the 'atxxxx') are separated; rather inefficient as requiring lots of back and forth with the DB. Using the current approach, query processing is entirely done at DB level. We are also able to profile the query at this level (query planner), identify where indexes should be used etc.

Re this issue, the `provider` attribute of a CareEntry is not properly encoded. I will post a fix shortly.

Many thanks -- Christian

**Comment by robert-hunter-nes** [comment]
Hi Christian

Thanks for getting back to me with the explanation there ragarding my query around the serialisation. I understand why you don't use the library for that then. Being able to have the query run on the database sounds excellent so I see why you do it that way now.

If it helps, I have raised a small PR https://github.com/ehrbase/ehrbase/pull/143 that has a fix for the provider name, and confirms it with a modified test which is working for me now.

The limitation of my fix is that it will only allow the provider name to save, it doesn't  save the identifier field. It's not actually functionality that I rrequire at the moment.

Thanks
Robert

**Comment by chevalleyc** [comment]
Many thanks Robert for your contribution!

Cheers -- Christian
