### ISSUE TITLE
Creating and retrieving flat composition

### ISSUE THREAD

**Issue by ghost** [ehrbase/ehrbase#396]
Hi,

I’m trying to create flat composition of a template using docker container. I’m facing issues mentioned below after restarting docker composer multiple times.

During first try I’m able to create a composition, But after restarting multiple times, If I commit a composition I will get an error as mentioned below:
{
“error”: “java.lang.IllegalArgumentException: Composition missing mandatory attribute: language”,
“status”: “Internal Server Error”
}

Secondly, I’m able to retrieve a composition using compositionId which is fetched after committing a composition. But after restarting, If I try to retrieve a same composition I can see different path coming up in the link attached below:

https://drive.google.com/file/d/1XhWp2BUR53VCkKt8V4LU6gHc0AwS2i3Q/view?usp=sharing

Please find the attached template for your reference.

https://drive.google.com/file/d/1zBIuVo9-E2s79f3-0O9nNtaFaBp4eaB-/view?usp=sharing

Thanks,
Raksha R

**Comment by stefanspiska** [comment]
The ctx shorcut is not supported right now:
"ctx/language"
try with 
"diagnosis/language|terminology": "ISO_639-1",
"diagnosis/language|code": "en",

I don't understand you second problem since you retrieving  to different compositions:
ehrbase/rest/ecis/v1/compositiond4fbb010-21cb-4ccf-84d8-ab83a15b2748
0/ehrbase/rest/ecis/v1/composition817379f4-00ff-4161-a03c-8f1bb4e46da1

**Comment by raksharaju23** [comment]
Hi,

The below mentioned paths works once started the service, i.e before restarting service.

"ctx/language"
"diagnosis/language|terminology": "ISO_639-1",
"diagnosis/language|code": "en"

But after restarting couple of times, throws an error:
{
“error”: “java.lang.IllegalArgumentException: Composition missing mandatory attribute: language”,
“status”: “Internal Server Error”
}

And, I'm retrieving the composition using same compositionId but could see different paths coming up.
I have updated the document.

**Comment by stefanspiska** [comment]
1. Can you post the result of /ehrbase/rest/ecis/v1/template/EHRN Diagnosis.v1 and /ehrbase/rest/openehr/v1/definition/template/adl1.4/EHRN Diagnosis.v1
2. Was the Template EHRN Diagnosis.v1  updated/changed during the runtime of the system
3.  Since the ip of your two request is different. A you running multiple instances of ehrbase on the same db.

**Comment by raksharaju23** [comment]
1. I have updated the result in the above mentioned link. Please have a look at it.
2. The template was not updated during the runtime.

I didn't understand the 3rd point mentioned.

**Comment by stefanspiska** [comment]
When I click on https://drive.google.com/file/d/1XhWp2BUR53VCkKt8V4LU6gHc0AwS2i3Q/view I can only see your old Reuest.
Can you please Provider a updated link.
