### ISSUE TITLE
DV_CODED_TEXT not persisted via FLAT JSON

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#480]
## Configuration information

{
    "ehrbase_version": "0.16.1",
    "openehr_sdk_version": "6f242df",
    "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
    "jvm_version": "Oracle Corporation 11.0.10+9",
    "os_version": "Linux amd64 5.4.0-1031-azure",
    "postgres_version": "PostgreSQL 11.6, compiled by Visual C++ build 1800, 64-bit"
}

## Steps to reproduce ## 

curl --location --request POST 'http://dca-alpha-ehr-api.azurewebsites.net/ehrbase/rest/ecis/v1/composition?ehrId=49c2ed8d-cda4-4aa7-8167-ee937d344118&templateId=IDCR%20-%20Adverse%20Reaction%20List.v1&committerName=Dr%20Franke&format=FLAT' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic ZWhyYmFzZS11c2VyOlN1cGVyU2VjcmV0UGFzc3dvcmQ=' \
--data-raw ' {
        "adverse_reaction_list/language|code": "en",
        "adverse_reaction_list/language|terminology": "ISO_639-1",
        "adverse_reaction_list/territory|code": "GB",
        "adverse_reaction_list/territory|terminology": "ISO_3166-1",
        "adverse_reaction_list/context/start_time": "2016-12-20T00:11:02.518+02:00",
        "adverse_reaction_list/context/setting|code": "238",
        "adverse_reaction_list/context/setting|value": "other care",
        "adverse_reaction_list/context/setting|terminology": "openehr",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/_uid": "19e3f66c-ec61-458b-81d9-5f7d81870289",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent|code": "304270095",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent|value": "Erythromycin",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent|terminology": "SNOMED-CT",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|code": "at0122",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|value": "Medication",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|terminology": "local",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:0|code": "422400008",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:0|value": "Vomiting",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:0|terminology": "SNOMED-CT",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/comment": "Reported by patient'\''s carer",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/last_updated": "2017-12-20T00:11:02.518+02:00",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/language|code": "en",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/language|terminology": "ISO_639-1",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/encoding|code": "UTF-8",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/encoding|terminology": "IANA_character-sets",
        "adverse_reaction_list/category|code": "433",
        "adverse_reaction_list/category|value": "event",
        "adverse_reaction_list/category|terminology": "openehr",
        "adverse_reaction_list/composer|name": "Dr Jonty Shannon"
    }'

## Actual result ##

  "composition": {
        "adverse_reaction_list/language|code": "en",
        "adverse_reaction_list/language|terminology": "ISO_639-1",
        "adverse_reaction_list/composer|name": "Dr Jonty Shannon",
        "adverse_reaction_list/territory|terminology": "ISO_3166-1",
        "adverse_reaction_list/territory|code": "GB",
        "adverse_reaction_list/context/setting|code": "238",
        "adverse_reaction_list/context/setting|terminology": "openehr",
        "adverse_reaction_list/context/setting|value": "other care",
        "adverse_reaction_list/context/start_time": "2016-12-20T02:11:02.518+02:00",
        "adverse_reaction_list/category|code": "433",
        "adverse_reaction_list/category|terminology": "openehr",
        "adverse_reaction_list/category|value": "event",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|value": "Medication",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|terminology": "local",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|code": "at0122",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/encoding|code": "UTF-8",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/encoding|terminology": "IANA_character-sets",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/language|terminology": "ISO_639-1",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/language|code": "en",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/last_updated": "2017-12-20T00:11:02.518+02:00",
        "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/comment": "Reported by patient's carer",
        "adverse_reaction_list/_uid": "2915bc11-9549-4d7f-80fe-b687285af88e::local.ehrbase.org::1"
    },
    "format": "FLAT",
    "templateId": "IDCR - Adverse Reaction List.v1",

The data is also missing from the CANONICAL JSON
## Expected result (Acceptance Criteria) ##

Should include the Erythromicin SNOMED coded node.
## Definition of Done ##

Returns DV_CODED_TEXT correctly

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
With https://github.com/ehrbase/ehrbase/pull/506 this works now.

Note that for https://ckm.apperta.org/ckm/templates/1051.57.71 I had to change the flat to

`{
  "adverse_reaction_list/language|code": "en",
  "adverse_reaction_list/language|terminology": "ISO_639-1",
  "adverse_reaction_list/territory|code": "GB",
  "adverse_reaction_list/territory|terminology": "ISO_3166-1",
  "adverse_reaction_list/context/start_time": "2016-12-20T00:11:02.518+02:00",
  "adverse_reaction_list/context/setting|code": "238",
  "adverse_reaction_list/context/setting|value": "other care",
  "adverse_reaction_list/context/setting|terminology": "openehr",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/_uid": "19e3f66c-ec61-458b-81d9-5f7d81870289",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent|code": "304270095",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent|value": "Erythromycin",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent|terminology": "SNOMED-CT",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|code": "at0122",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|value": "Medication",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/category|terminology": "local",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_event:0/manifestation:0|code": "422400008",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_event:0/manifestation:0|value": "Vomiting",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_event:0/manifestation:0|terminology": "SNOMED-CT",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_event:0/comment": "Reported by patient'''s carer",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/last_updated": "2017-12-20T00:11:02.518+02:00",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/language|code": "en",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/language|terminology": "ISO_639-1",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/encoding|code": "UTF-8",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/encoding|terminology": "IANA_character-sets",
  "adverse_reaction_list/category|code": "433",
  "adverse_reaction_list/category|value": "event",
  "adverse_reaction_list/category|terminology": "openehr",
  "adverse_reaction_list/composer|name": "Dr Jonty Shannon"
}`

since some paths where wrong.

**Comment by freshehr** [comment]
Confirmed fixed thanks - sorry about the mixup between .opt version and json
