### ISSUE TITLE
Error while building docker

### ISSUE THREAD

**Issue by shuhaib3** [ehrbase/ehrbase#521]
#14 [builder  8/46] RUN echo "host  all  all   0.0.0.0/0  scram-sha-256" >> /var/lib/postgresql/pgdata/pg_hba.conf
#14 sha256:9d70020c5775bf1c3a18f71c8bf3d6578404947a934fccd4da12af8b5f8af57a
#14 DONE 0.6s

#15 [builder  9/46] RUN echo "listen_addresses='*'" >> /var/lib/postgresql/pgdata/postgresql.conf
#15 sha256:1c945de3062e8cfec398e24f17ae34b10838e89ae468a2b28bec7255cf7d63f3
#15 DONE 0.6s

#16 [builder 10/46] RUN apk add --update postgresql=11.11-r0   build-base   git   flex   bison
#16 sha256:9c79caf24254ff5c8ad7b2ebff5520ad8a1332302b974be8a39373ba6a3ffd25
#16 0.567 fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
#16 1.646 fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
#16 2.275 ERROR: unsatisfiable constraints:
#16 2.298   postgresql-11.12-r0:
#16 2.298     breaks: world[postgresql=11.11-r0]
#16 ERROR: executor failed running [/bin/sh -c apk add --update postgresql=${PG_MAJOR}-r0   build-base   git   flex   bison]: exit code: 1
------
 > [builder 10/46] RUN apk add --update postgresql=11.11-r0   build-base   git   flex   bison:
------
executor failed running [/bin/sh -c apk add --update postgresql=${PG_MAJOR}-r0   build-base   git   flex   bison]: exit code: 1

**Comment by birgerhaarbrandt** [comment]
@shuhaib3 The issue is not raised in a helpful way. Can you please provide a meaningful description?

**Comment by shuhaib3** [comment]
@birgerhaarbrandt i was trying to change the context path in application-docker.yml for spring profile docker but the docker build is getting failing with Dockerfile provided and the above error is what am getting when trying to build with the dockerfile in repo.

**Comment by jakesmolka** [comment]
Hey @shuhaib3! Why do you want to change the `application-docker.yml`? If you just want to apply different configuration settings to our pre-build docker image(s) you can overwrite everything via environment variables. If that's the case have a look at
- [our documentation on how to run EHRbase with Docker compose and have an `.env` file for overwriting the config](https://ehrbase.readthedocs.io/en/latest/03_development/04_docker_images/01_ehrbase/02_use_image/index.html#run-ehrbase-db-with-docker-compose)
- [and my explanation of the general mechanics of our config on the openEHR forums](https://discourse.openehr.org/t/list-of-available-override-the-application-properties-like-database-settings-in-ehrbase/1580/5)

If that's not the case, could you state your specific changes and what commands you are running exactly? Otherwise it is not possible to reproduce the problem.
