### ISSUE TITLE
500 Error on CORS preflight

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#669]
## Configuration information

- EHRbase version: 0.17.2
- openEHR_SDK version: 321ef09
- Archie version: 1.0.3
- PostgreSQL version: PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-      gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
- Java Runtime version: Oracle Corporation 11.0.13+8
- Operating System version: Linux amd64 5.10.16.3-microsoft-standard-WSL2

## Steps to reproduce ## 

curl --request OPTIONS \
  --url 'http://localhost:8080/ehrbase/rest/ecis/v1/composition/?format=FLAT&templateId=NCD&ehrId=5ac0400b-3b1d-4beb-bf27-9dec9c11751d' \
  --header 'Access-Control-Request-Method: GET' \
  --header 'Origin: http://localhost:3000' \
  --header 'Referer: http://localhost:3000/'

## Actual result ##

500 Internal Error

## Expected result (Acceptance Criteria) ##

200 OK

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by mobilars** [comment]
The following forum topic could be related, or could be a separate issue: https://discourse.openehr.org/t/create-new-ehr-using-postman-rest-services/1982/7

For the issue in the forum page, I'm only getting the problem when there is authentication turned on, and for POST requests. My setup is one where the web application and ehrbase each run on their own ports, but is 'brought together' on port 80 by a proxy-function in nginx (intended to overcome CORS issues):

web application -> nginx --> ehrbase 

There is a server side error message when doing the request:

_java.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins cannot contain the special value “*” since that cannot be set on the “Access-Control-Allow-Origin” response header. To allow credentials to a set of origins, list them explicitly or consider using “allowedOriginPatterns” instead.
at org.springframework.web.cors.CorsConfiguration.validateAllowCredentials(CorsConfiguration.java:473)
at org.springframework.web.cors.CorsConfiguration.checkOrigin(CorsConfiguration.java:577)
at org.springframework.web.cors.DefaultCorsProcessor.checkOrigin(DefaultCorsProcessor.java:174)_

But, it could be a separate issue from that reported, since I can't see if its explicitly on the preflight and I'm only getting it on post. A server log error might help to see if it's the same issue.

**Comment by subigre** [comment]
Hi @sidharthramesh, Hi @mobilars 

Could you please try again with the current development version of EHRbase: `0.17.3-SNAPSHOT`

I tried to reproduce locally using Docker ( `ehrbase/ehrbase:next`) and command line (`java -jar application-0.17.3-SNAPSHOT.jar`) and it works fine.


```json
{
    "ehrbase_version": "0.17.3-SNAPSHOT",
    "openehr_sdk_version": "1e26bf1",
    "archie_version": "1.0.4",
    "jvm_version": "AdoptOpenJDK 11.0.11+9",
    "os_version": "Windows 10 amd64 10.0",
    "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}
```

```bash
$ curl --request OPTIONS --url "http://localhost:8080/ehrbase/rest/openehr/v1/ehr/331120ec-6988-463e-afc3-8717d8bdc99f" \
--header "Access-Control-Request-Method: GET" \
--header "Origin: http://localhost:3000" \
--header "Referer: http://localhost:3000/" -i

HTTP/1.1 200
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,POST
Access-Control-Max-Age: 1800
Allow: GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH
Content-Length: 0
Date: Mon, 29 Nov 2021 09:02:49 GMT
```

**Comment by sidharthramesh** [comment]
CORS requests are working as expected in version 0.17.3-SNAPSHOT.

**Comment by mobilars** [comment]
Good to hear it's been fixed. I can't even do the "mvn package" without errors, so can't really test. Is 0.17.3-SNAPSHOT available pre-built via docker already so I don't have to build it myself? Or is that an earlier version?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project service: Compilation failure: Compilation failure:
[ERROR] /C:/fkj/ehrbase-git/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[356,68] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /C:/fkj/ehrbase-git/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[356,20] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /C:/fkj/ehrbase-git/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[68,35] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /C:/fkj/ehrbase-git/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[73,36] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /C:/fkj/ehrbase-git/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[79,28] reference to Record is ambiguous

**Comment by mobilars** [comment]
I'm still getting the same error

**Comment by subigre** [comment]
Dear @mobilars, the docker image for `0.17.3-SNAPSHOT` is available using the tag: `ehrbase/ehrbase:next`.

PS: Regarding your issue, this is probably linked to the JDK version that you use to build the application. Could you please check and ensure that you use JDK 11.
```bash
java -version
```

**Comment by mobilars** [comment]
OK, I'm using latest Java version (from Oracle).  java version "17.0.1" 2021-10-19 LTS. So I should downgrade to get it to work? 

I'm now using the docker-image ehrbase/ehrbase:next (same result)

The difference is that I'm using basic authentication and you are not using authentication. Could you try with a username/password for BASIC authentication and see if it works for you? When using authentication, the CORS-rules are stricter.

That said, it could very well be a local issue here. I'll be very embarrased if it is :-)
