### ISSUE TITLE
Request returning unexpected HTTP-Status Code on a Bad Request  with DELETE composition

### ISSUE THREAD

**Issue by richter122-goe** [ehrbase/ehrbase#678]
## Configuration information

    <ehrbase_version>0.17.2</ehrbase_version>
    <openehr_sdk_version>fac6c67</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Oracle Corporation 11.0.12+7</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 

1. Send an example composition to the server
  Template: [ZLG_Testdaten.opt.txt](https://github.com/ehrbase/ehrbase/files/7603612/ZLG_Testdaten.opt.txt)
2. Delete the composition using
   Endpoint: DELETE {{host}}/ehrbase/rest/openehr/v1/ehr/:ehrId/composition/:compositionId
   - Enter compositionId
   - Leave ehrId blank

## Actual result ##

Leaving the ehrId or both ehrId and compositionId blank like ( DELETE {host}/ehrbase/rest/openehr/v1/ehr//composition/)
leads to 401 Unauthorized.

![image](https://user-images.githubusercontent.com/64580653/143458543-bfb7a536-724d-44b7-b8ce-47ee9a26eb29.png)

## Expected result (Acceptance Criteria) ##

Like:  
I guess 400 Bad Request would be appropiate?
Leaving the compositionId blank gives back 405.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by richter122-goe** [comment]
Just an update:
I tried the :next-Docker-Image (related to an other now fixed issue) and there was no change in behaviour.
<ehrbase_version>0.17.3-SNAPSHOT</ehrbase_version>
    <openehr_sdk_version>1e26bf1</openehr_sdk_version>
    <archie_version>1.0.4</archie_version>
    <jvm_version>Oracle Corporation 11.0.13+8</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

**Comment by subigre** [comment]
Dear @richter122-goe 


I just tried locally with the following config:
```json
{
    "ehrbase_version": "0.17.3-SNAPSHOT",
    "openehr_sdk_version": "1e26bf1",
    "archie_version": "1.0.4",
    "jvm_version": "AdoptOpenJDK 11.0.11+9",
    "os_version": "Windows 10 amd64 10.0",
    "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}
```

```yaml
    environment:
      ADMIN_API_ACTIVE: 'true'
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: user
      SECURITY_AUTHPASSWORD: Azerty1234
      SECURITY_AUTHADMINUSER: admin
      SECURITY_AUTHADMINPASSWORD: Azerty123456
```

and here are the results:
- No user = `401 Unauthorized`
- User = `403 Forbidden`
- Admin with empty EHR ID = `401 Unauthorized`
- Admin with invalid EHR ID =  `404 Not Found` 
- Admin with invalid or empty Composition ID = `404 Not Found`
- Admin with valid EHR ID and Composition ID = `204 No Content`

Based on the status code `401 Unauthorized`, I guess that you are running EHRbase with security (Basic Auth/OAuth2) enabled?
If yes and if you are correctly authenticated with admin user, the error `401 Unauthorized` comes from the implementation of `HttpFirewall`. 

By default, Spring Security uses `StrictHttpFirewall` implementation to validate the URL. Using `http://localhost:8080/ehrbase/rest/admin/ehr//composition/`, request is rejected because the URL contains a potentially malicious string ( `//`).

In my opinion, even if the status code `401 Unauthorized` looks strange, current behavior is correct knowing that is a security exception.

**Comment by richter122-goe** [comment]
Dear subigre,
thank you for your replay and additional information. Yes, i am using Basic Auth.

I guess I didn't think far enough here, but considering the HttpFirewall and the resulting string `http://localhost:8080/ehrbase/rest/admin/ehr//composition/` the `401 Unathorized`-Response makes sense.
