### ISSUE TITLE
CORS issue when security is enabled and using nginx proxy

### ISSUE THREAD

**Issue by subigre** [ehrbase/ehrbase#684]
@mobilars, I create a new ticket as your issue seems different from the original one (https://github.com/ehrbase/ehrbase/issues/669)

## Background 

- https://discourse.openehr.org/t/create-new-ehr-using-postman-rest-services/1982
- https://github.com/ehrbase/ehrbase/issues/669#issuecomment-981053817
- https://github.com/ehrbase/ehrbase/issues/669#issuecomment-981706520

**Comment by mobilars** [comment]
I must admit I find CORS very confusing, so might be I'm doing things wrong here. But the curl responses with authentication turned off or on is different, and it failes with authentication on .

On a server with authentication turned on, with request going through nginx proxy forwarding between local ports 80 -> 8080. 

_C:\fkj\web-ehr>curl -u user:secret --request OPTIONS --url "http://localhost/ehrbase/rest/openehr/v1/ehr/47a44b09-f320-433e-a448-cd6bc699c695" --header "Access-Control-Request-Method: GET" --header "Origin: http://localhost" --header "Referer: http://localhost/lab" -i
HTTP/1.1 401
Server: nginx/1.21.4
Date: Mon, 29 Nov 2021 15:18:29 GMT
Content-Length: 0
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
WWW-Authenticate: Basic realm="Realm"_

After I turned authentication off (changed env-file to SECURITY_AUTHTYPE=none)

C:\fkj\web-ehr>curl -u user:secret --request OPTIONS --url "http://localhost:8080/ehrbase/rest/openehr/v1/ehr/47a44b09-f320-433e-a448-cd6bc699c695" --header "Access-Control-Request-Method: GET" --header "Origin: http://localhost" --header "Referer: http://localhost/lab" -i
HTTP/1.1 200
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,POST
Access-Control-Max-Age: 1800
Allow: GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH
Content-Length: 0
Date: Mon, 29 Nov 2021 15:15:47 GMT

BUT, what makes me think it might be a local issue or some configuration error in nginx is that when I run directly towards the ehrbase server on port 8080 (so not via the nginx on port 80), it works... 

C:\fkj\web-ehr>curl -u user:secret --request OPTIONS --url "http://localhost:8080/ehrbase/rest/openehr/v1/ehr/47a44b09-f320-433e-a448-cd6bc699c695" --header "Access-Control-Request-Method: GET" --header "Origin: http://localhost:8080" --header "Referer: http://localhost:8080/lab" -i
HTTP/1.1 200
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0
Date: Mon, 29 Nov 2021 15:19:33 GMT

**Comment by sidharthramesh** [comment]
Most of our apps communicate with EHRBase from the browser, and we share your frustration with CORS errors. @DharsanB  @ATHULKNAIR.

And we had a very similar error when enabling Basic Authentication on the reverse proxy (nginx in this case) and CORS on the downstream service (EHRBase in this case). The problem was, The CORS headers are supposed to be returned by EHRBase, but since the Authentication check is done before that, it never reaches the server, and the reverse proxy returns a 401 without the headers. This is obviously a failed CORS preflight.

A solution to that was handling all the OPTIONS request separately and returning an appropriate response with the correct headers and only check for Authentication for the other requests.

However, this hack will not be necessary if Authentication is enabled on EHRBase (However, I've never tested that).

So how are you enabling Basic Auth? On EHRBase itself, or on your Nginx server?

**Comment by mobilars** [comment]
Answering the last part first. Will read the beginning a few times before replying to that :-) 

I'm running ehrbase using the docker compose described in 3.4.1.2.2 here https://ehrbase.readthedocs.io/en/latest/03_development/04_docker_images/01_ehrbase/02_use_image/index.html

It has an env-file that defaults to SECURITY_AUTHTYPE=BASIC

But when I set it to SECURITY_AUTHTYPE=none the authentication is turned off. 

So the authentication is in the ehrbase server, not nginx. It seems you had the authentication in nginx rather than ehrbase? Might be similar problem, but in my case the request does seem to reach the server and cause the following error in the ehrbase log. This is a new feature in spring boot apparently. 

ava.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins cannot contain the special value "*" since that cannot be set on the "Access-Control-Allow-Origin" response header. To allow credentials to a set of origins, list them explicitly or consider using "allowedOriginPatterns" instead.

at org.springframework.web.cors.CorsConfiguration.validateAllowCredentials(CorsConfiguration.java:473)

**Comment by mobilars** [comment]
Ehrbase seems to accept the requests (also with authentication) when the web client claims it's accessing ehrbase on the port that ehrbase is actually running, but not when it's on a different port. I changed my ngxinx to rewrite the origin and referer from whatever it is to http://localhost:8080 (which is where ehrbase is running rather than the port 80 that nginx is running and the web client runs. Then it works. Probably not smart from a security point of view as I'm basically cancelling CORS, but not a big issue for me in my test. Here's my nginx in case anyone's interested. I suspect one has to edit the spring files according to this (https://stackoverflow.com/questions/64892592/cors-enabled-in-spring-boot-with-angular-still-cors-errors) to get it to work properly, but then I have to build it myself and it won't build and I don't really need it enough to downgrade to v11 of java if that's what it'd take. 

The following nginx configuration basically means that nginx is getting a request with headers

Origin: http://localhost
Referer: http://localhost/lab

and nginx deletes these header values and just puts in the following instead

Origin: http://localhost:8080
Referer: http://localhost:8080

Then, for some reason, the ehrbase accepts the request. 

_#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location /ehrbase/ {
    		proxy_pass http://localhost:8080/ehrbase/;
		#proxy_set_header Authorization "Basic dXNlcjpzZWNyZXQ=";
		proxy_set_header Referer "";
		proxy_set_header Referer "http://localhost:8080";
		proxy_set_header Origin "";
		proxy_set_header Origin "http://localhost:8080";

		#proxy_set_header Authorization $http_authorization;
		#proxy_pass_header Authorization;
        }
        location / {
    		proxy_pass http://localhost:4200/;
        }
    }
}_

**Comment by mobilars** [comment]
OK, so downgrading to jdk 11 did let me build it, as you predicted.

**Comment by subigre** [comment]
Good 👍 If you are able to build EHRbase locally, I will push a new branch with some additional CORS config. I hope that it will fix your issue.

PS: You can have both JDK installed and switch between one or the other depending on the project you are working on.

**Comment by subigre** [comment]
Could please try the following branch: https://github.com/ehrbase/ehrbase/tree/619_cors_issue_security_nginx

Dependending if you use the JAR or build the Docker image, the following should fix the issue:
```yaml
# application-custom.yml
web:
  cors:
    allow-credentials: true
    allowed-origin-patterns: '*'
```

```yaml
# docker-compose.yml
    environment:
      WEB_CORS_ALLOWCREDENTIALS: 'true'
      WEB_CORS_ALLOWEDORIGINPATTERNS: '*'
```

**Comment by mobilars** [comment]
Thanks. I need to let it rest for a couple of days, but will try later. I don't have an application-custom.yml. Can I use the application.yml (how does it choose between them???)

**Comment by subigre** [comment]
Sorry for the late reply. 
Yes, you can add the properties in the default `application.yml`.
