### ISSUE TITLE
Fully specified Dockerfiles (build and postgres)

### ISSUE THREAD

**Issue by connec** [ehrbase/ehrbase#77]
Currently this repository provides a [`Dockerfile`](https://github.com/ehrbase/ehrbase/blob/develop/application/Dockerfile) for the EHRbase application that depends on building the JAR locally, as well as a reference to a [postgres image](https://hub.docker.com/layers/ehrbaseorg/ehrbase-database-docker/11.5/images/sha256-7809c1b04213f249a1bb64ee7f67e01aeb190c08f7f7d9c0cbb3c047bbdcf472) that's suitable for use with EHRbase.

I wanted to have a fully specified, independently reproducible build for an EHRbase instance suitable for developing against locally (e.g. not optimised in any way for deployment) and wound up creating [connec/ehrbase-docker](https://github.com/connec/ehrbase-docker). The `Dockerfile`s in that repo contain all the steps necessary to build a functional [EHRbase application image](https://github.com/connec/ehrbase-docker/blob/master/ehrbase/Dockerfile) and a suitable [PostgreSQL image](https://github.com/connec/ehrbase-docker/blob/master/ehrbase-postgres/Dockerfile) with the necessary extensions and database setup, with no dependence on any local configuration (apart from docker itself, of course, and network access).

Before making a PR, I wanted to check if there's interest in maintaining this style of `Dockerfile` in the EHRbase repo itself?

Furthermore, to ease developer onboarding it would be helpful if the application docker image was made available through the [EHRbase docker org](https://hub.docker.com/u/ehrbaseorg) (like the [`ehrbase-database-docker`](https://hub.docker.com/r/ehrbaseorg/ehrbase-database-docker) image is currently). Is there a reason this isn't currently the case? Are there any contributions that could help make that happen?

Finally, in the same vein of simplifying developer onboarding, I think more prominent instructions in the README for running the application using docker would be great, particularly when combined with pre-published images. If you agree I'd like to make a PR for this also.

**Comment by Geisterfalle** [comment]
Hi Chris,

thanks for raising this issue! Having a proper docker image for EHRbase is certainly in our interest and we planned to have this done until the end of this month. I will ask @testautomation and @axelsiebert for feedback and such an addition is certainly highly welcome. 

The explanation why we have not done this before is that we were focussing on EHRbase developers/contributoris that would need to build the code locally. As there is now increasing interest to use EHRbase for app development, this is certainly the next step to make the entry as friendly and easy as possible.

Birger

**Comment by axelsiebert** [comment]
Hi Chris,

thank you for yur suggestion and your code. We discussed your proposal and think that it would be very useful for all developers of EHRbase.

We have some remarks and suggestions for your implementation that might improve it as well.

1. We should use the already provided docker image for the database from Docker. There are also some environment variables that can be used to provide the postgres user credentials which should be always possible. This image also uses the newer 11.5 Version of Postgres.

2. You are currently fetching the 0.9.0 release branch inside your image. If we want a special version of EHRbase inside the docker we should make this target version configurable via environment variables. If there is no version specified the master should be the default branch. The start CMD can be defined with wildcards then to use the build output file, i.e. `COPY --from=package /ehrbase/application/target/application-*.jar ehrbase.jar`

3. If we want to integrate your solution we need some License information on your code. Since we use the Apache 2.0 this would be one suggestion.

**Comment by connec** [comment]
Hi @axelsiebert, thanks for your feedback! I'll respond to each item in turn:

1. The reason I did not use the provided docker image is that the Dockerfile for it is not included in the repo and I wanted a "fully specified, independently reproducible" build. I agree that credentials ought to be configurable via arguments – this can be done through environment variables as supported by the base image (see [here](https://github.com/docker-library/docs/tree/master/postgres#environment-variables)).

   The reason the image uses an older version of PostgreSQL is that `jsquery@ver_1.1.1` (the latest tagged version) does not support PostgreSQL ≥10. Whilst this has been fixed in the repo, a new version has not been tagged and I didn't want to depend on an untagged version. I think I will raise an issue on that repo to tag a new release, meaning the image could trivially be updated to PostgreSQL 11 or 12.

2. That is a very good point! I didn't think about that. I'll take a look at parameterising that asap.

3. Also a very good point! I will add a license asap also.

Let me know what you think re: point 1. I can see in [Docker Hub](https://hub.docker.com/layers/ehrbaseorg/ehrbase-database-docker/11.5/images/sha256-7809c1b04213f249a1bb64ee7f67e01aeb190c08f7f7d9c0cbb3c047bbdcf472) the instructions from the Dockerfile that built the image, but I can't see any of `install-temporal-tables.sh`, `install-jsquery.sh`, or `prepare-databases.sh`, which prevents reproducing builds of the image.

**Comment by axelsiebert** [comment]
Hi @connec ,

thanks for the explanation. I will try to give some answers to you ;-)

1. That makes sense. We also have an repository for the docker images and I think we should provide this as open source as well. I will commmunicate this to the core team.

The docker file from there uses the last untagged version of jsquery from the master branch. But I think you are right to use a tagged version. I'm looking forward to your feedback from the jsquery guys.

We should then also include the environment parameters from the base image into the README since they are security relevant for the project.

**Comment by connec** [comment]
>     1. We should then also include the environment parameters from the base image into the README since they are security relevant for the project.

Agreed! I'll put something in my docs, but if the official EHRbase PostgreSQL image is open-sourced then it may be unnecessary to use mine.

I'll keep my eye on the jsquery issue – I'm a little worried since that issue was posted in May last year and there has been no response 😄

**Comment by axelsiebert** [comment]
We will open the Docker repository asap. Just got the information that this will be necessary for open source ;-)

Thanks, we are looking forward to hear something new

**Comment by connec** [comment]
This is a little orthogonal, but we've also been investigating (cloud) managed database deployments of PostgreSQL for EHRbase, where of course the versioning behaviour is emulated and `jsquery` is not available.

Is it written anywhere what the advantage of the `temporal_tables` and `jsquery` extensions are over the functions in [`cloud-db-*.sql`](https://github.com/ehrbase/ehrbase/tree/develop/base/db-setup) and regular JSON(B) functions, respectively? Is the intention to maintain both options forever or will the `temporal_tables`/`jsquery` be dropped?

**Comment by Geisterfalle** [comment]
There is no clear statement about this. I'm sure @chevalleyc can say something about this. My understanding is that these dependencies will be dropped. Not sure if this will happen with the new version of Postgres or if this is independent.

**Comment by chevalleyc** [comment]
Some Postgresql extensions are external contributions (jsquery and temporal_tables). Using these is an operational choice as there are pros and cons. F.e. jsquery supports very nicely GIN indexing on the '@' (contains) operator, BUT it is not supported by all cloud providers...

In the future, on a EhrBase perspective, I guess jsquery will be replaced by a proper jsonpath (assuming the performance is ok). temporal_tables is already replaced by a pl/pgsql function. 

Today: to avoid using both these extensions, create the db with: https://github.com/ehrbase/ehrbase/blob/develop/base/db-setup/cloud-db-setup.sql (AFAIK this is already used by NHS-X Scotland)

**Comment by connec** [comment]
@chevalleyc thanks for your input! We are indeed using `cloud-db-setup.sql`.

From past experience, PostgreSQL's JSONB functions can be very performant and have good index utilisation when using the 'containment' (`@>`) operator – https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING. Unfortunately I don't know enough about AQL to know how easy a conversion that would be. It's potentially something I'd be interested in exploring, as time allows, if you are open to contributions in that area?

**Comment by connec** [comment]
Sorry for the long time without a response. I've updated [connec/ehrbase-docker](https://github.com/connec/ehrbase-docker) to allow configuring most versions through build arguments and I have also added the Apache 2.0 license to the repository, to keep thing simple.

Of your original concerns, the only one I've not addressed is the issue with PostgreSQL 11/12. Since https://github.com/postgrespro/jsquery/issues/36 has had no updates, and similarly https://github.com/arkhipov/temporal_tables/pull/48, I wonder if it would be worth forking these repositories in order to create tags and build from them? Alternatively, whatever was done to create the official images could be used.

**Comment by axelsiebert** [comment]
Hi @connec,

I would like to integrate your docker files into the official docker repository.

Since we migrated the Java version up to 11 you should update these dependencies. We recommed the usage of the adopkopenjdk 11.

I think it should not be a problem to downgrade the postgres version back to 10 until at least the temporal_tables plugin tags a new version.

As I understood Christian correctly the jsquery plugin increases the performance but is no critical dependency.
