### ISSUE TITLE
Inconsistent query response in tests

### ISSUE THREAD

**Issue by gregorberger** [ehrbase/ehrbase#858]
## Configuration information

- EHRbase version: 0.20.0
- openEHR_SDK version: 1.18.0-SNAPSHOT
- Archie version: 1.0.4
- PostgreSQL version: PostgreSQL 14.2
- Java Runtime version: openjdk 17.0.1 2021-10-19
- Operating System version: MacOs Monterey

## Steps to reproduce ## 

run `robot -t "COMPOSITION JSON with no time zone using AQL" robot/COMPOSITION_TESTS/COMPOSITION_WITH_DIFFERENT_TIME_ZONES/"COMPOSITION_JSON_no_time_zone".robot`

Expected result is 
```json
{
    "columns": [
        {
            "name": "#0",
            "path": "/context/start_time/value"
        },
        {
            "name": "#1",
            "path": "/data[at0001]/origin/value"
        },
        {
            "name": "#2",
            "path": "/data[at0001]/events[at0002]/time/value"
        }
    ],
    "q": "SELECT a/context/start_time/value , o/data[at0001]/origin/value,o/data[at0001]/events[at0002]/time/value  from EHR e  contains COMPOSITION a[openEHR-EHR-COMPOSITION.minimal.v1] contains OBSERVATION o [openEHR-EHR-OBSERVATION.minimal.v1]  where a/uid/value ='e0573524-ac97-497d-99c8-4c1f9de5278a::default::1'",
    "rows": [
        [
            "2019-01-28T21:22:19.501",
            "2019-01-28T21:22:19.552",
            "2019-01-28T21:22:19.562"
        ]
    ]
} 
```

But when running `robot -t "D-502 Execute Ad-HOc Query - Get Data" robot/QUERY_SERVICE_TESTS/A.1_EXECUTE_AD-HOC_QUERY/"A.1__a_Loaded_DB".robot`
The expected result is:
```json
{
    "meta": {
        "_type": "RESULTSET",
        "_created": "2019-10-18T18:02:36.259Z",
        "_executed_aql": "SELECT e/ehr_id/value as uid FROM EHR e CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.minimal.v1] CONTAINS INSTRUCTION"
    },
    "q": "SELECT e/ehr_id/value as uid FROM EHR e CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.minimal.v1] CONTAINS INSTRUCTION",
    "columns": [
        {
            "name": "uid",
            "path": "/ehr_id/value"
        }
    ],
    "rows": [
        [
            "66a26b59-ff89-433b-927f-5ad82ebe4077"
        ]
    ]
}
```

## Actual result ##

As you can see in the first expected result "columns" is before "q", but in the second "q" is before "columns". I also saw this problem in other files with query response.

## Expected result (Acceptance Criteria) ##

The query response should be in the same order, because tests fail when the difference is detected. 

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @gregorberger,
I have analyzed above case.
In ehrbase\tests\robot\_resources\keywords, there is file called **aql_query_keywords.robot**. This file contains keyword **check response (LOADED DB): returns correct content**, where Python function _compare_jsons_ignoring_properties_ is performing the difference between expected and actual JSON files. Fifth argument of this Python function is ignore_order, which has by default True value - meaning that it can ignore the order of JSON objects.
You can use it with False value on ingore_order argument, and only in that case, test case will fail due to order of JSON objects is different in expected and actual JSON files.

Please let me know if my explanation is clear / needs further investigation by developers.
Thank you!

**Comment by gregorberger** [comment]
@vladislavploaia Thank you for the response, my parameter was set to false for some reason.
