### ISSUE TITLE
use of [ expresion to filter ] in aql 

### ISSUE THREAD

**Issue by xarranzm** [ehrbase/ehrbase#925]
## Configuration information

- EHRbase version: v0.20.0
- openEHR_SDK version:
- Archie version:
- PostgreSQL version: 11.5
- Java Runtime version: openjdk-11
- Operating System version: Ubuntu 20.04.1 LTS

## Steps to reproduce ## 

{
    "q": "SELECT c/feeder_audit/originating_system_item_ids[type='Sample']/id  FROM ehr e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.document.v0]"
}

## Actual result ##

{
    "error": "Bad Request",
    "message": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: syntax error at or near \"Sample\"\n ....

## Expected result (Acceptance Criteria) ##

The list of ID with type 'Sample'

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @xarranzm ,
Could you please provide the OPT and COMPOSITION content you placed before running this AQL?
Thank you!

**Comment by xarranzm** [comment]
Hello,

The syntax error no depends on OPT or composition. 

We have the openEHR-EHR-COMPOSITION.document.v0 in multiples templates and c/feeder_audit/originating_system_item_ids[type='Sample']/id comes from refrerence model.

if you need and OPT and composition tell me and I updatede te note

**Comment by vladislavploaia** [comment]
Hello @xarranzm,
I think I already found the documentation reference for above issue.
Here is the link: https://specifications.openehr.org/releases/QUERY/latest/AQL.html#_class_expressions
_Class expressions are used in the **FROM**_
So, I suppose, your AQL is not a valid one.
CC: @stefanspiska, @HolgerReiseVSys

**Comment by birgerhaarbrandt** [comment]
Hi @joseblancots and @xarranzm,

support of predicates is not (yet) fully implemented. You should be able to use archetype_id and name attributes, but types (to my knowledge, will have to test) will currently not be accepted as predicates. 

We are currently further enhancing the AQL capabilities of EHRbase and this will likely be part of it. This means that we will not address this on short-notice, but add the functionality until the end of the year. 

Would it be an alternative to put a filter on the attribute into the WHERE clause for now?

**Comment by jpwiedekopf** [comment]
Hi @birgerhaarbrandt, I currently have the same issue in my ETL pipeline for [Patientenaufenthalt](https://ckm.highmed.org/ckm/templates/1246.169.590). My current problem is that I want to retrieve a composition matching the _Versorgungstellenkontakt_ by ID (for updating). The template however has three included `openEHR-EHR-CLUSTER.case_identification.v0` archetypes (_Versorgungsfall_, _Abteilungsfall_, _Versorgungsstellenkontakt_), and I can't for the life of me filter for the _Versorgungsstellenkontakt_ using AQL:

```
SELECT c/uid/value AS uid
FROM EHR e 
CONTAINS COMPOSITION c 
WHERE c/archetype_details/template_id/value = 'Patientenaufenthalt'
AND c/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.case_identification.v0 AND name/value='Versorgungsstellenkontakt']/items[at0001]/value = '889406681'
```

doesn't work due to the above reason.

If I leave out the `AND` part in the `[]`, the result is actually empty when it shouldn't be (I know for a fact that I have a composition matching the predicate). That's another issue, I'd guess, but it makes it very unwieldy to find the latest composition for this template in an EHR (retrieve all compositions and filter client-side).

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
