### ISSUE TITLE
Location header in response has incorrect uri

### ISSUE THREAD

**Issue by abebehailu** [ehrbase/ehrbase#933]
## Configuration information

- EHRbase version: 0.21.1
- openEHR_SDK version: 1.19.0
- Archie version: 2.0.1
- PostgreSQL version: PostgreSQL 13.4
- Java Runtime version: Oracle Corporation 11.0.15
- Operating System version: Linux amd64 4.18.0

## Steps to reproduce ## 

1. Create EHR by making a post request to https://www.mydomain.com/ehrbase/rest/openehr/v1/ehr/
2. Check the location header in the response

Note: we get the same behavior when creating EHR with id and when posting compositions.

My theory is that the call to the method getBaseEnvLinkURL on the following line is the issue *https://github.com/ehrbase/ehrbase/blob/ef8ed6148cb0a480d92f0b3d88cd5a33e872c9ea/rest-openehr/src/main/java/org/ehrbase/rest/openehr/OpenehrEhrController.java#L139*.
The implementation of the method is found here *https://github.com/ehrbase/ehrbase/blob/ef8ed6148cb0a480d92f0b3d88cd5a33e872c9ea/rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java#L117*.  I believe that this line fetches the whole request uri rather than only the base. The uri is then appended with  "/rest/openehr/v1/ehr/" + ehrId leading to the bug in question. 

## Actual result ##

Value is in the format: https://www.mydomain.com/ehrbase/rest/openehr/v1/ehr/de7205e7-fb70-4b5e-bd2d-51cc0ac81f1d//rest/openehr/v1/ehr/de7205e7-fb70-4b5e-bd2d-51cc0ac81f1d

## Expected result (Acceptance Criteria) ##

https://www.mydomain.com/ehrbase/rest/openehr/v1/ehr/de7205e7-fb70-4b5e-bd2d-51cc0ac81f1d

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @abebehailu,
Checked the location headers and I confirm that the same is reproducible in EHRBase version **0.22.0**
Bug reported in JIRA for tracking purposes: https://jira.vitagroup.ag/browse/CDR-481
Will let you know in case of any updates.

CC: @stefanspiska

**Comment by andrew-nds** [comment]
We've seen the same bug in 0.21.1, although it's not blocking us as the correct UID is returned in the ETag header. 

I wanted to highlight that the [openEHR API spec](https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#composition-composition-post) examples show all composition endpoints returning the full version UID (`8849182c-82ad-4088-a07f-48ead4180515::openEHRSys.example.com::2`) rather than the shorter versioned object UID (`8849182c-82ad-4088-a07f-48ead4180515`).

That makes sense to me as calling `GET` with the Location header from a POST/PUT/GET should consistently return that specific version, but in this case GETting a composition with the shorter versioned object UID will return a newer version if one exists.

Lastly, in case it helps, we believe EHRBase 0.19 and below returned different Location headers for different endpoints - PUT returned the full version id, but POST always returned just the versioned object id.

**Comment by vladislavploaia** [comment]
Hello @abebehailu ,
Issue was fixed. Ticket https://jira.vitagroup.ag/browse/CDR-704
EHRbase version: 0.24.0-SNAPSHOT
openEHR_SDK version: 1.24.0-SNAPSHOT
![image](https://user-images.githubusercontent.com/100927963/218097064-d6c2e72c-535a-4aac-9356-8b546d51e3e4.png)
![image](https://user-images.githubusercontent.com/100927963/218097113-3b86b279-1538-477e-9978-153dbdf5aac2.png)
![image](https://user-images.githubusercontent.com/100927963/218097177-c4db9a89-9b24-4a6d-b08b-ff8845763c76.png)
Ticket closed.
CC: @vidi42 , @HolgerReiseVSys , @dmitrytulba
